name: Release Github Packages

on:
  push:
    branches: [ master ]

jobs:

  prepare:
    name: Prepare Image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils        
          APP_ARTIFACTID=`xmllint --xpath '/*[local-name()="project"]/*[local-name()="artifactId"]/text()' ./app/pom.xml`
          APP_VERSION=`xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' ./app/pom.xml`
          echo "export APP_ARTIFACTID=$APP_ARTIFACTID" > ./VARIABLES_FILE
          echo "export APP_VERSION=$APP_VERSION" >> ./VARIABLES_FILE
          cat ./VARIABLES_FILE
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: VARIABLES_FILE
          path: ./VARIABLES_FILE

  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: ["prepare"]
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: VARIABLES_FILE
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - run: |
          source ./VARIABLES_FILE
          echo $APP_ARTIFACTID
          echo $APP_VERSION
          docker build . -t ghcr.io/${{ github.actor}}/${{ secrets.image }}:latest --build-arg "APP_ARTIFACTID=$APP_ARTIFACTID" --build-arg "APP_VERSION=$APP_VERSION"
          docker push ghcr.io/${{ github.actor}}/${{ secrets.image }}:latest
          
